FROM python:3.7-alpine3.15 as base

RUN mkdir -p /app
WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY ./src/ /app/
ENV FLASK_APP=logic_resource.py

CMD flask run -h 0.0.0 -p 8001
