apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hw2-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hw2-secret
                  key: postgres-root-password
            - name: POSTGRES_DB
              value: hw2

#
#
#
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: mongo-root-username
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: mongo-root-password
#
#                  db:
#                    image: postgres
#                    restart: always
#                    environment:
#                      POSTGRES_PASSWORD: example
#
#                  adminer:
#                    image: adminer
#                    restart: always
#                    ports:
#                      - 8080:8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mongodb-service
#spec:
#  selector:
#    app: mongodb
#  ports:
#    - protocol: TCP
#      port: 27017
#      targetPort: 27017
