FROM python:3.7-alpine3.15 as base

RUN mkdir -p /app
WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt
RUN apk --update --no-cache add python3-dev libffi-dev gcc musl-dev make libevent-dev build-base
RUN apk add postgresql-dev
RUN pip3 install -r requirements.txt

COPY ./src/ /app/
ENV FLASK_APP=user_resource.py

CMD flask run -h 0.0.0 -p 8000
