kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hw10
  name: role-secret-access
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-secret-binding
  namespace: hw10
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hw10
roleRef:
  kind: Role
  name: role-secret-access
  apiGroup: rbac.authorization.k8s.io
