apiVersion: apps/v1
kind: Deployment
metadata:
  name: bondiana
  labels:
    app: bondiana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bondiana
  template:
    metadata:
      labels:
        app: bondiana
    spec:
      containers:
        - name: bondiana-container
          image: diacrome/bondiana:0.4
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bondiana-config
                  key: databaseUrl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-data-getter
  labels:
    app: external-data-getter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-data-getter
  template:
    metadata:
      labels:
        app: external-data-getter
    spec:
      containers:
        - name: external-data-getter-container
          image: diacrome/moex-bonds:0.15
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bondiana-config
                  key: databaseUrl
